version: 0.1

phases:
  pre_build:
    commands:
      - echo 'prebuild done'
  build:
    commands:
      - javac ApplicationRunner.java
  post_build:
    commands:
      - echo "build completed"
artifacts:
  files:
  - '**/*'
