version: 0.2


phases:
  pre_build:
    commands:      
      - echo 'prebuild test'
  build:
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends openssh-client
      - javac ApplicationRunner.java
  post_build:
    commands:
      - echo "build completed"
artifacts:
  files:
  - '**/*'
