version: 0.2


phases:
  pre_build:
    commands:      
      - echo 'prebuild test'
  build:
    commands:     
      - javac ApplicationRunner.java
  post_build:
    commands:
      - echo "build completed"
artifacts:
  files:
  - '**/*'
